### ISSUE TITLE
模块

### ISSUE THREAD

**Issue by xwh8965** [leafmoes/leafmoes#1]
哥在吗 请问下可以帮忙定制一个模块功能吗，有预算。

**Comment by leafmoes** [comment]
> 哥在吗 请问下可以帮忙定制一个模块功能吗，有预算。

什么功能？预算多少？

**Comment by xwh8965** [comment]
> > 哥在吗 请问下可以帮忙定制一个模块功能吗，有预算。
> 
> 什么功能？预算多少？

QQ群发功能 可以吗

**Comment by leafmoes** [comment]
应该没问题，但是请你说清楚一点
我需要你的具体的需求和预算。

**Comment by leafmoes** [comment]
> > > 哥在吗 请问下可以帮忙定制一个模块功能吗，有预算。
> > 
> > 什么功能？预算多少？
> 
> QQ群发功能 可以吗

应该没问题，但是请你说清楚一点
我需要你的具体的需求和预算。

**Comment by xwh8965** [comment]
> > > > 哥在吗 请问下可以帮忙定制一个模块功能吗，有预算。
> > > 
> > > 什么功能？预算多少？
> > 
> > QQ群发功能 可以吗
> 
> 应该没问题，但是请你说清楚一点
> 我需要你的具体的需求和预算。

好的 就是简单的做个群发功能，方便加个v吗 详谈

**Comment by xwh8965** [comment]
> > > > 哥在吗 请问下可以帮忙定制一个模块功能吗，有预算。
> > > 
> > > 什么功能？预算多少？
> > 
> > QQ群发功能 可以吗
> 
> 应该没问题，但是请你说清楚一点
> 我需要你的具体的需求和预算。

哥 在吗

**Comment by xwh8965** [comment]
哥在吗 能收到吗



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月27日(周三) 下午2:51
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [leafmoes/leafmoes] 模块 (Issue #1)




    
哥在吗 请问下可以帮忙定制一个模块功能吗，有预算。
  
什么功能？预算多少？
  
QQ群发功能 可以吗
  
应该没问题，但是请你说清楚一点
 我需要你的具体的需求和预算。

**Comment by leafmoes** [comment]
> 哥在吗 能收到吗
> 
> 
> 
> ---原始邮件---
> 发件人: ***@***.***&gt;
> 发送时间: 2024年3月27日(周三) 下午2:51
> 收件人: ***@***.***&gt;;
> 抄送: ***@***.******@***.***&gt;;
> 主题: Re: [leafmoes/leafmoes] 模块 (Issue #1)
> 
> 
> 
> 
>     
> 哥在吗 请问下可以帮忙定制一个模块功能吗，有预算。
>   
> 什么功能？预算多少？
>   
> QQ群发功能 可以吗
>   
> 应该没问题，但是请你说清楚一点
>  我需要你的具体的需求和预算。
>  
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

邮箱谈吧：asmclk@163.com
